### ISSUE TITLE
fatal: clone of 'git://github.com/RusticiSoftware/TinCanJS.git' into submodule path 'GolfExample_TCAPI/scripts/TinCanJS' failed

### ISSUE THREAD

**Issue by SeemaSP** [RusticiSoftware/TinCan_Prototypes#43]
Having this issue when I ran the command:
git submodule update --init --recursive
OR
git clone --recursive https://github.com/RusticiSoftware/TinCan_Prototypes.git

**Comment by brianjmiller** [comment]
This was a problem with the way submodules were originally set up. I've pushed a commit to fix the problem so that submodule sources point at `https` URLs instead of `git` ones (the latter requiring a permission in our organization). You should be able to either re-clone or in your existing clone do:

    git fetch
    git merge origin/master
    git submodule sync
    git submodule update --init --recursive

Let us know if this does not solve the problem.

**Comment by SeemaSP** [comment]
Still having issue. Apparently the url is still git. I got the following error:
fatal: unable to connect to github.com:
github.com: Temporary failure in name resolution

fatal: clone of 'git://github.com/RusticiSoftware/TinCanJS.git' into submodule path 'scripts/TinCanJS' failed
Failed to recurse into submodule path 'StatementViewer/resources'
